# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6c6bc6cf6f486aa69d97a847f050641487ceb89ec234a644c5e52a05c98db03df6cae645306645f3e244c6086cbdfd08e269e8bce44955c096b3578a0d30e86

test:
  secret_key_base: 5d8f3b0236c9d7030bcde8155f60d47cde7e58cff1f2b6202cad35a29bcc9f6e9e5da19b4876841bdde2ae1014b8354ebf938a7538bba5c20dd4e48c8a24e316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
